# Generated by Django 5.2.1 on 2025-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Содержимое статьи"),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles_photo/", verbose_name="Изображение"),
        ),
    ]
