# Generated by Django 5.2.1 on 2025-06-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/", verbose_name="Фотография товара"),
        ),
    ]
