# Generated by Django 5.2.1 on 2025-07-03 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание товара"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(verbose_name="Цена продукта"),
        ),
    ]
